[package]
name = "grain"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow-array = "57.0.0"
arrow-buffer = "57.0.0"
arrow-ord = "57.0.0"
indexmap = "2.12.0"

[dependencies.bitvec]
version = "1.0.1"
default-features = false
features = ["alloc"]
